### ISSUE TITLE
Tareas Pendientes

### ISSUE THREAD

**Issue by EstherRM85** [EstherRM85/ProyectoWeb-Medicina#13]
Unir base de datos con poyecto

**Comment by kokoyoana** [comment]
Unir base de datos con proyecto

**Comment by kokoyoana** [comment]
Unir base de datos con proyecto

**Comment by kokoyoana** [comment]
Unir base de datos con proyecto

**Comment by EstherRM85** [comment]
Union BDD con Proyecto

**Comment by kokoyoana** [comment]
Unir base de datos con proyecto
